language: node_js
node_js:
  - 6.11.2

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
    - DATABASE_URL=postgres://postgres@localhost/travisdb
